### ISSUE TITLE
Italics

### ISSUE THREAD

**Issue by Pszek** [chicaumgomes/material-ocean-next-theme-plus#1]
At last the theme with extremely well coverage for JSX. Two things:
- making React components attributes italic would be really nice.
- In the theme page  in VS Market You could have provided address to the Git repo.

Good work, keep it up like that.

**Comment by fthiagogv** [comment]
Thanks for comment.
This is my first extension, and I'm not familiar with all.
I will update for react in soon. Also I will put git repo on readme.

Thanks again.
